name: Deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies (frontend)
        working-directory: ./frontend
        run: npm install

      - name: Build frontend
        working-directory: ./frontend
        run: npm run dev

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set up Docker Compose
        run: docker-compose --version

      - name: Start database
        run: docker-compose up -d db

      - name: Build and start app
        run: docker-compose up --build app

      # Add your deployment steps below
      - name: Deploy
        run: echo "Add deployment steps here (e.g., upload to server, deploy to cloud, etc.)"
